# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: communication.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x63ommunication.proto\"-\n\x16RsyncCompletionRequest\x12\x13\n\x0b\x66older_name\x18\x01 \x01(\t\">\n\x1aSnapshotCompletionResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2n\n\x12RsyncNotifications\x12X\n TakeSnapshotAfterRsyncCompletion\x12\x17.RsyncCompletionRequest\x1a\x1b.SnapshotCompletionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'communication_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_RSYNCCOMPLETIONREQUEST']._serialized_start=23
  _globals['_RSYNCCOMPLETIONREQUEST']._serialized_end=68
  _globals['_SNAPSHOTCOMPLETIONRESPONSE']._serialized_start=70
  _globals['_SNAPSHOTCOMPLETIONRESPONSE']._serialized_end=132
  _globals['_RSYNCNOTIFICATIONS']._serialized_start=134
  _globals['_RSYNCNOTIFICATIONS']._serialized_end=244
# @@protoc_insertion_point(module_scope)
