# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import communication_pb2 as communication__pb2


class RsyncNotificationsStub(object):
    """Define the service for notifying the server about rsync completion
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TakeSnapshotAfterRsyncCompletion = channel.unary_unary(
                '/RsyncNotifications/TakeSnapshotAfterRsyncCompletion',
                request_serializer=communication__pb2.RsyncCompletionRequest.SerializeToString,
                response_deserializer=communication__pb2.SnapshotCompletionResponse.FromString,
                )


class RsyncNotificationsServicer(object):
    """Define the service for notifying the server about rsync completion
    """

    def TakeSnapshotAfterRsyncCompletion(self, request, context):
        """Notify the server about a successful rsync transfer
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RsyncNotificationsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TakeSnapshotAfterRsyncCompletion': grpc.unary_unary_rpc_method_handler(
                    servicer.TakeSnapshotAfterRsyncCompletion,
                    request_deserializer=communication__pb2.RsyncCompletionRequest.FromString,
                    response_serializer=communication__pb2.SnapshotCompletionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'RsyncNotifications', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RsyncNotifications(object):
    """Define the service for notifying the server about rsync completion
    """

    @staticmethod
    def TakeSnapshotAfterRsyncCompletion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RsyncNotifications/TakeSnapshotAfterRsyncCompletion',
            communication__pb2.RsyncCompletionRequest.SerializeToString,
            communication__pb2.SnapshotCompletionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
